apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: http-app-scaledobject
spec:
  scaleTargetRef:
    name: http-app

  minReplicaCount: 1
  maxReplicaCount: 10

  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 10
          policies:
            - type: Percent
              value: 50
              periodSeconds: 10
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
            - type: Percent
              value: 100
              periodSeconds: 10

  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-server.monitoring.svc.cluster.local:9090
        threshold: "1"
        query: rate(http_requests_total[1m])